services:
  app:
    image: php:8.3-fpm
    container_name: codeigniter_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - default

  web:
    image: nginx:alpine
    container_name: codeigniter_nginx
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - default

networks:
  default:
    driver: bridge
