services:
  app:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    container_name: codeigniter_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - default

  web:
    image: nginx:alpine
    container_name: codeigniter_nginx
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - default

  db:
    image: mysql:8.0
    container_name: codeigniter_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: c4
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
